// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import java.util.Objects;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class BackupVar_createVar_a25d6200de_Test {

    @Test
    public void testCreateVar_Success() {
        String testVar = "Test";
        BackupVar<String> backupVar = BackupVar.createVar(testVar);

        assertNotNull(backupVar);
        assertEquals(testVar, backupVar.getVar());
    }

    @Test
    public void testCreateVar_Null() {
        BackupVar<Object> backupVar = BackupVar.createVar(null);

        assertNotNull(backupVar);
        assertEquals(null, backupVar.getVar());
    }
}
