// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import java.util.Objects;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class BackupVar_toString_2393b88875_Test {

    @Mock
    private BackupVar_toString_2393b88875_Test backupVar;

    @Before
    public void setup() {
        when(backupVar.toString()).thenReturn(MoreObjects.toStringHelper(backupVar)
            .add("var", "testVar")
            .toString());
    }

    @Test
    public void testToString() {
        assertEquals("BackupVar_toString_2393b88875_Test{var=testVar}", backupVar.toString());
    }

    @Test
    public void testToStringWithDifferentVar() {
        when(backupVar.toString()).thenReturn(MoreObjects.toStringHelper(backupVar)
            .add("var", "differentVar")
            .toString());
        assertEquals("BackupVar_toString_2393b88875_Test{var=differentVar}", backupVar.toString());
    }
}
