// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Objects;

public class BackupVar_hashCode_77d48187ef_Test {
    private BackupVar backupVar;

    @BeforeEach
    public void setUp() {
        backupVar = Mockito.mock(BackupVar.class);
    }

    @Test
    public void testHashCode_success() {
        String var = "test";
        Mockito.when(backupVar.getVar()).thenReturn(var);
        int expectedHashCode = Objects.hash(var);
        int actualHashCode = backupVar.hashCode();
        assertEquals(expectedHashCode, actualHashCode);
    }

    @Test
    public void testHashCode_nullVar() {
        Mockito.when(backupVar.getVar()).thenReturn(null);
        int expectedHashCode = Objects.hash((Object) null);
        int actualHashCode = backupVar.hashCode();
        assertEquals(expectedHashCode, actualHashCode);
    }
}
