// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.telegram.abilitybots.api.util.Pair;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class BackupMap_add_6ed6527a16_Test {

    private Set<Pair<Integer, String>> entries;

    @BeforeEach
    public void setUp() {
        entries = new HashSet<>();
    }

    @Test
    public void testAdd_success() {
        Pair<Integer, String> kvPair = new Pair<>(1, "Test");
        assertTrue(add(kvPair));
        assertTrue(entries.contains(kvPair));
    }

    @Test
    public void testAdd_failure() {
        Pair<Integer, String> kvPair = new Pair<>(1, "Test");
        entries.add(kvPair);
        assertFalse(add(kvPair));
    }

    public boolean add(Pair<Integer, String> kvPair) {
        return entries.add(kvPair);
    }
}
