// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.telegram.abilitybots.api.util.Pair;
import java.util.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class BackupMap_iterator_f338f83ea2_Test {

    private List<Pair<Integer, String>> entries;

    @BeforeEach
    public void setup() {
        entries = new ArrayList<>();
        entries.add(new Pair<>(1, "One"));
        entries.add(new Pair<>(2, "Two"));
    }

    @Test
    public void testIterator_success() {
        Iterator<Pair<Integer, String>> iterator = entries.iterator();

        assertTrue(iterator.hasNext());
        assertEquals(new Pair<>(1, "One"), iterator.next());
        assertEquals(new Pair<>(2, "Two"), iterator.next());
        assertFalse(iterator.hasNext());
    }

    @Test
    public void testIterator_empty() {
        entries.clear();
        Iterator<Pair<Integer, String>> iterator = entries.iterator();

        assertFalse(iterator.hasNext());
        assertThrows(NoSuchElementException.class, iterator::next);
    }
}
