// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import java.util.HashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class BackupMap_size_5b2cadc6cd_Test {

    @InjectMocks
    BackupMap backupMap;

    @Mock
    Map<String, String> entries;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSize_whenMapIsEmpty() {
        when(entries.size()).thenReturn(0);
        int actualSize = backupMap.size();
        assertEquals(0, actualSize, "Size of the map should be 0");
    }

    @Test
    public void testSize_whenMapHasElements() {
        Map<String, String> tempMap = new HashMap<>();
        tempMap.put("key1", "value1");
        tempMap.put("key2", "value2");

        when(entries.size()).thenReturn(tempMap.size());
        int actualSize = backupMap.size();
        assertEquals(2, actualSize, "Size of the map should be 2");
    }
}
