// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import org.telegram.abilitybots.api.util.Pair;
import java.util.*;

public class BackupMap_BackupMap_00bdea8d8f_Test {

    private BackupMap backupMap;

    @Mock
    private Pair<String, String> mockPair;

    @BeforeEach
    public void setUp() {
        backupMap = new BackupMap();
    }

    @Test
    public void testBackupMap_addSuccess() {
        // TODO: Change the values of "key" and "value" to the ones you want to test
        String key = "testKey";
        String value = "testValue";
        when(mockPair.getKey()).thenReturn(key);
        when(mockPair.getValue()).thenReturn(value);

        backupMap.add(mockPair);

        assertEquals(value, backupMap.get(key));
    }

    @Test
    public void testBackupMap_addFailure() {
        // TODO: Change the values of "key" and "value" to the ones you want to test
        String key = "testKey";
        String value = "testValue";
        when(mockPair.getKey()).thenReturn(key);
        when(mockPair.getValue()).thenReturn(value);

        backupMap.add(mockPair);
        // TODO: Change the value of "otherKey" to a key not present in the map
        String otherKey = "otherKey";

        assertEquals(null, backupMap.get(otherKey));
    }
}
