// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.telegram.abilitybots.api.util.Pair;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class BackupMap_toMap_177b69758d_Test {

    private List<Pair<String, Integer>> entries;
    
    @BeforeEach
    public void setUp() {
        entries = new ArrayList<>();
    }

    @Test
    public void testToMapWithNonEmptyEntries() {
        entries.add(new Pair<>("One", 1));
        entries.add(new Pair<>("Two", 2));
        entries.add(new Pair<>("Three", 3));

        Map<String, Integer> expected = new HashMap<>();
        expected.put("One", 1);
        expected.put("Two", 2);
        expected.put("Three", 3);

        Map<String, Integer> actual = toMap();

        assertEquals(expected, actual);
    }

    @Test
    public void testToMapWithEmptyEntries() {
        Map<String, Integer> expected = new HashMap<>();

        Map<String, Integer> actual = toMap();

        assertEquals(expected, actual);
    }

    public Map<String, Integer> toMap() {
        Map<String, Integer> map = new HashMap<>();
        entries.forEach(e -> map.put(e.a(), e.b()));
        return map;
    }
}
