// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import java.util.Objects;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BackupVar_equals_5bdc7536f0_Test {

    private BackupVar<String> backupVar1;
    private BackupVar<String> backupVar2;
    private BackupVar<String> backupVar3;

    @BeforeEach
    public void setUp() {
        backupVar1 = new BackupVar<>("TestVar1");
        backupVar2 = new BackupVar<>("TestVar1");
        backupVar3 = new BackupVar<>("TestVar2");
    }

    @Test
    public void testEquals_sameObject() {
        assertEquals(true, backupVar1.equals(backupVar1), "The same object should be equal to itself");
    }

    @Test
    public void testEquals_sameValue() {
        assertEquals(true, backupVar1.equals(backupVar2), "Objects with the same value should be equal");
    }

    @Test
    public void testEquals_differentValue() {
        assertEquals(false, backupVar1.equals(backupVar3), "Objects with different values should not be equal");
    }

    @Test
    public void testEquals_null() {
        assertEquals(false, backupVar1.equals(null), "Object should not be equal to null");
    }

    @Test
    public void testEquals_differentClass() {
        assertEquals(false, backupVar1.equals("TestVar1"), "Object should not be equal to an object of a different class");
    }
}
