// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.telegram.abilitybots.api.util.Pair;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BackupMap_BackupMap_4961455e5b_Test {

    private BackupMap<Integer, String> backupMap;

    @BeforeEach
    void setUp() {
        backupMap = new BackupMap<>(new HashMap<>());
    }

    @Test
    void testBackupMapWithValidInput() {
        Map<Integer, String> map = new HashMap<>();
        map.put(1, "One");
        map.put(2, "Two");

        backupMap = new BackupMap<>(map);
        assertEquals(2, backupMap.size());

        Pair<Integer, String> pair1 = Pair.of(1, "One");
        Pair<Integer, String> pair2 = Pair.of(2, "Two");

        assertTrue(backupMap.contains(pair1));
        assertTrue(backupMap.contains(pair2));
    }

    @Test
    void testBackupMapWithEmptyInput() {
        Map<Integer, String> map = new HashMap<>();
        backupMap = new BackupMap<>(map);
        assertEquals(0, backupMap.size());
    }

    @Test
    void testBackupMapWithNullInput() {
        assertThrows(NullPointerException.class, () -> new BackupMap<>(null));
    }
}
