// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mapdb.DB;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import java.io.File;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class MapDBContext_onlineInstance_8608b685ab_Test {

    @Mock
    private DB dbMock;

    private String name;
    private File file;

    @Before
    public void setUp() {
        name = "testDB";
        file = new File(name);
    }

    @After
    public void tearDown() {
        file.delete();
    }

    @Test
    public void testOnlineInstance_success() {
        DBContext result = MapDBContext.onlineInstance(name);
        assertNotNull(result);
        assertTrue(file.exists());
    }

    @Test(expected = Exception.class)
    public void testOnlineInstance_failure() {
        when(DBMaker.fileDB(anyString()).make()).thenThrow(new RuntimeException());
        MapDBContext.onlineInstance(name);
    }
}
