// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

import java.util.HashSet;
import java.util.Set;

@RunWith(MockitoJUnitRunner.class)
public class MapDBContext_getSet_75512bd881_Test {

    @Mock
    private DB db;

    private MapDBContext context;

    @Before
    public void setUp() {
        context = new MapDBContext(db);
    }

    @Test
    public void testGetSet_Success() {
        String setName = "testSet";
        Set<String> expectedSet = new HashSet<>();
        expectedSet.add("test1");
        expectedSet.add("test2");
        when(db.<String>hashSet(setName, Serializer.JAVA).createOrOpen()).thenReturn(expectedSet);

        Set<String> actualSet = context.getSet(setName);

        assertEquals(expectedSet, actualSet);
    }

    @Test(expected = ClassCastException.class)
    public void testGetSet_Failure() {
        String setName = "testSet";
        when(db.<String>hashSet(setName, Serializer.JAVA).createOrOpen()).thenThrow(new ClassCastException());

        context.getSet(setName);
    }
}
