// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import com.google.common.base.MoreObjects;
import org.mapdb.Atomic;
import java.util.Objects;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class MapDBVar_equals_5bdc7536f0_Test {

    @Test
    public void testEqualsSameObject() {
        MapDBVar<String> mapDBVar1 = new MapDBVar<>("TestVar");
        assertTrue(mapDBVar1.equals(mapDBVar1));
    }

    @Test
    public void testEqualsDifferentObjectSameValue() {
        MapDBVar<String> mapDBVar1 = new MapDBVar<>("TestVar");
        MapDBVar<String> mapDBVar2 = new MapDBVar<>("TestVar");
        assertTrue(mapDBVar1.equals(mapDBVar2));
    }

    @Test
    public void testEqualsDifferentObjectDifferentValue() {
        MapDBVar<String> mapDBVar1 = new MapDBVar<>("TestVar1");
        MapDBVar<String> mapDBVar2 = new MapDBVar<>("TestVar2");
        assertFalse(mapDBVar1.equals(mapDBVar2));
    }

    @Test
    public void testEqualsNullObject() {
        MapDBVar<String> mapDBVar1 = new MapDBVar<>("TestVar");
        assertFalse(mapDBVar1.equals(null));
    }

    @Test
    public void testEqualsDifferentClassObject() {
        MapDBVar<String> mapDBVar1 = new MapDBVar<>("TestVar");
        String str = "TestVar";
        assertFalse(mapDBVar1.equals(str));
    }
}
