// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mapdb.DB;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class MapDBContext_contains_c8ec37739e_Test {

    @Mock
    private DB db;

    private MapDBContext mapDBContext;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        mapDBContext = new MapDBContext(db);
    }

    @Test
    public void testContains_WhenNameExists_ReturnsTrue() {
        String existingName = "existingName";
        when(db.exists(existingName)).thenReturn(true);

        boolean result = mapDBContext.contains(existingName);

        assertTrue(result);
        verify(db, times(1)).exists(existingName);
    }

    @Test
    public void testContains_WhenNameDoesNotExist_ReturnsFalse() {
        String nonExistingName = "nonExistingName";
        when(db.exists(nonExistingName)).thenReturn(false);

        boolean result = mapDBContext.contains(nonExistingName);

        assertFalse(result);
        verify(db, times(1)).exists(nonExistingName);
    }
}
