// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import com.google.common.base.MoreObjects;
import org.mapdb.Atomic;
import java.util.Objects;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class MapDBVar_get_b5609f9376_Test {

    private Atomic.Var<Object> var;
    private MapDBVar<Object> mapDBVar;

    @BeforeEach
    public void setUp() {
        var = Mockito.mock(Atomic.Var.class);
        mapDBVar = new MapDBVar<>(var);
    }

    @Test
    public void testGet_Success() {
        Object expectedValue = new Object();
        when(var.get()).thenReturn(expectedValue);

        Object actualValue = mapDBVar.get();

        assertEquals(expectedValue, actualValue, "Returned value does not match expected value");
    }

    @Test
    public void testGet_NullValue() {
        when(var.get()).thenReturn(null);

        Object actualValue = mapDBVar.get();

        assertNull(actualValue, "Returned value is not null");
    }

    @Test
    public void testGet_ExceptionThrown() {
        when(var.get()).thenThrow(new RuntimeException());

        assertThrows(RuntimeException.class, () -> mapDBVar.get(), "Expected get() to throw, but it didn't");
    }
}
