// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.mapdb.Atomic;
import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mapdb.Serializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.telegram.abilitybots.api.util.Pair;
import java.io.IOException;
import java.util.*;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class MapDBContext_MapDBContext_6b37b6733a_Test {

    private DB db;
    private ObjectMapper objectMapper;
    private MapDBContext mapDBContext;

    @Before
    public void setUp() {
        db = mock(DB.class);
        objectMapper = new ObjectMapper();
        objectMapper.enableDefaultTyping();
        mapDBContext = new MapDBContext(db);
    }

    @Test
    public void testMapDBContextSuccess() {
        assertNotNull(mapDBContext);
        assertEquals(db, mapDBContext.getDB());
        assertEquals(objectMapper, mapDBContext.getObjectMapper());
    }

    @Test(expected = NullPointerException.class)
    public void testMapDBContextFailure() {
        new MapDBContext(null);
    }
}
