// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mapdb.DB;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;
import static org.mockito.Mockito.doThrow;

@RunWith(MockitoJUnitRunner.class)
public class MapDBContext_close_62bc6aa102_Test {

    @Mock
    private DB db;

    @Before
    public void setUp() {
        Mockito.when(db.isClosed()).thenReturn(false);
    }

    @Test
    public void testClose_whenDbIsOpen_thenShouldCloseWithoutError() {
        // Arrange
        MapDBContext dbContext = new MapDBContext(db);

        // Act
        dbContext.close();

        // Assert
        Mockito.verify(db).close();
    }

    @Test(expected = RuntimeException.class)
    public void testClose_whenDbCloseThrowsException_thenShouldThrowRuntimeException() {
        // Arrange
        doThrow(new IllegalStateException()).when(db).close();
        MapDBContext dbContext = new MapDBContext(db);

        // Act
        dbContext.close();

        // Assert
        // Expecting exception
    }
}
