// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import com.google.common.base.MoreObjects;
import org.mapdb.Atomic;
import java.util.Objects;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class MapDBVar_MapDBVar_e20fcfc0bc_Test {

    @Mock
    Atomic.Var<String> mockVar;

    @InjectMocks
    MapDBVar<String> mapDBVar;

    @Test
    public void testMapDBVar_WhenVarIsValid() {
        assertNotNull(mapDBVar);
        verify(mockVar, times(1)).get();
    }

    @Test
    public void testMapDBVar_WhenVarIsNull() {
        Atomic.Var<String> nullVar = null;
        assertThrows(NullPointerException.class, () -> new MapDBVar<>(nullVar));
    }
}
