// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.db;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mapdb.DB;
import org.mapdb.Serializer;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class MapDBContext_getMap_7c12f84e62_Test {

    @Mock
    private DB db;

    @InjectMocks
    private MapDBContext mapDBContext;

    @BeforeEach
    public void setUp() {
        when(db.hashMap(any(String.class), any(Serializer.class), any(Serializer.class))).thenReturn(db.hashMap("test", Serializer.JAVA, Serializer.JAVA));
    }

    @Test
    public void testGetMapSuccess() {
        Map<String, String> map = mapDBContext.getMap("test");
        assertNotNull(map, "Map should not be null");
    }

    @Test
    public void testGetMapFailure() {
        Exception exception = null;
        try {
            mapDBContext.getMap(null);
        } catch (Exception e) {
            exception = e;
        }
        assertNotNull(exception, "Exception should not be null");
    }
}
