// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.builder.AbilityBuilder;
import org.telegram.abilitybots.api.objects.Locality;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Ability_locality_b3534143bc_Test {

    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setup() {
        abilityBuilder = Mockito.mock(AbilityBuilder.class);
    }

    @Test
    public void testLocalityWithUser() {
        Locality type = Locality.USER;
        Mockito.when(abilityBuilder.locality(type)).thenReturn(abilityBuilder);
        AbilityBuilder result = abilityBuilder.locality(type);
        assertEquals(result, abilityBuilder);
    }

    @Test
    public void testLocalityWithAll() {
        Locality type = Locality.ALL;
        Mockito.when(abilityBuilder.locality(type)).thenReturn(abilityBuilder);
        AbilityBuilder result = abilityBuilder.locality(type);
        assertEquals(result, abilityBuilder);
    }
}
