// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Ability_input_8190398a06_Test {

    @InjectMocks
    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testInput() {
        int argNum = 5;
        assertEquals(abilityBuilder, abilityBuilder.input(argNum));
        assertEquals(argNum, abilityBuilder.getArgNum());
    }

    @Test
    public void testInputNegative() {
        int argNum = -5;
        assertEquals(abilityBuilder, abilityBuilder.input(argNum));
        assertEquals(argNum, abilityBuilder.getArgNum());
    }
}
