// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Ability_hashCode_77d48187ef_Test {
    private Ability ability;

    @BeforeEach
    public void setUp() {
        ability = mock(Ability.class);
    }

    @Test
    public void testHashCode_success() {
        Mockito.when(ability.hashCode()).thenReturn(12345);
        int actual = ability.hashCode();
        int expected = 12345;
        assertEquals(expected, actual);
    }

    @Test
    public void testHashCode_differentObject() {
        Ability anotherAbility = mock(Ability.class);
        Mockito.when(anotherAbility.hashCode()).thenReturn(67890);
        int actual = anotherAbility.hashCode();
        int expected = 67890;
        assertEquals(expected, actual);
    }
}
