// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Ability_info_a15f81a3b6_Test {

    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setUp() {
        abilityBuilder = new AbilityBuilder();
    }

    @Test
    public void testInfo_withValidInfo() {
        String info = "Test info";
        abilityBuilder.info(info);
        assertEquals(info, abilityBuilder.getInfo());
    }

    @Test
    public void testInfo_withNullInfo() {
        String info = null;
        abilityBuilder.info(info);
        assertNull(abilityBuilder.getInfo());
    }

    // TODO: Add more test cases as per requirement
}
