// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Ability_info_6c001fcedc_Test {

    @InjectMocks
    private Ability ability;

    private String info;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        info = "Test Info";
        ability.setInfo(info);
    }

    @Test
    public void testInfo() {
        String expectedOutput = "Test Info";
        assertEquals(expectedOutput, ability.info());
    }

    @Test
    public void testInfoFailure() {
        String expectedOutput = "Wrong Info";
        assertNotEquals(expectedOutput, ability.info());
    }
}
