// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.bot.AbilityBot;
import org.telegram.telegrambots.meta.api.objects.Message;
import org.telegram.telegrambots.meta.api.objects.Update;
import java.util.function.Consumer;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Ability_action_b78c919a90_Test {

    @Mock
    private AbilityBot bot;

    @Mock
    private Update update;

    @Mock
    private Message message;

    private Ability ability;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);

        when(update.getMessage()).thenReturn(message);

        ability = Ability
                .builder()
                .name("action")
                .info("test action")
                .locality(ALL)
                .privacy(PUBLIC)
                .action(ctx -> System.out.println("Action executed"))
                .post(ctx -> System.out.println("Post processing"))
                .build();

        bot.onUpdateReceived(update);
    }

    @Test
    public void testAction() {
        Consumer<MessageContext> action = ability.action();
        assertEquals("Action executed", action.accept(update.getMessage()));
    }

    @Test
    public void testActionWithNullMessage() {
        when(update.getMessage()).thenReturn(null);
        Consumer<MessageContext> action = ability.action();
        assertEquals("Action executed", action.accept(null));
    }
}
