// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Ability_name_f580dccbfc_Test {

    @Test
    public void testNameWhenNameIsNotNull() {
        // TODO: Replace "John Doe" with the actual name
        String expectedName = "John Doe";

        // TODO: Initialize the class which has the name() method and replace null with the actual instance
        Object instance = null;

        String actualName = instance.name();
        assertEquals(expectedName, actualName, "Expected name does not match the actual name");
    }

    @Test
    public void testNameWhenNameIsNull() {
        String expectedName = null;

        // TODO: Initialize the class which has the name() method with null name and replace null with the actual instance
        Object instance = null;

        String actualName = instance.name();
        assertEquals(expectedName, actualName, "Expected name does not match the actual name");
    }
}
