// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;

public class Ability_builder_db771f4bc7_Test {

    @Mock
    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testBuilderNotNull() {
        AbilityBuilder ab = AbilityBuilder.builder();
        assertNotNull(ab, "Builder should not be null");
    }

    @Test
    public void testBuilderNotSame() {
        AbilityBuilder ab1 = AbilityBuilder.builder();
        AbilityBuilder ab2 = AbilityBuilder.builder();
        assertNotSame(ab1, ab2, "Builders should not be same object");
    }
}
