// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class Ability_AbilityBuilder_84c5f5f112_Test {

    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setUp() {
        abilityBuilder = new AbilityBuilder();
    }

    @Test
    public void testStatsEnabled() {
        assertFalse(abilityBuilder.statsEnabled, "StatsEnabled should be initialized as false");
    }

    @Test
    public void testReplies() {
        assertNotNull(abilityBuilder.replies, "Replies should be initialized");
        assertTrue(abilityBuilder.replies.isEmpty(), "Replies should be initialized as empty");
    }

    @Test
    public void testAddReply() {
        // TODO: Replace with actual reply object
        Object reply = new Object();

        abilityBuilder.addReply(reply);

        assertFalse(abilityBuilder.replies.isEmpty(), "Replies should not be empty after adding a reply");
        assertEquals(1, abilityBuilder.replies.size(), "Replies size should be 1 after adding a reply");
        assertEquals(reply, abilityBuilder.replies.get(0), "First reply should be the one that was added");
    }
}
