// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.telegram.abilitybots.api.bot.AbilityBot;
import org.telegram.abilitybots.api.objects.Privacy;
import org.telegram.abilitybots.api.objects.Ability.AbilityBuilder;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Ability_privacy_05900c2887_Test {
    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setup() {
        abilityBuilder = AbilityBot.builder();
    }

    @Test
    public void testPrivacyMethodWithPublicPrivacy() {
        Privacy privacy = Privacy.PUBLIC;
        abilityBuilder.privacy(privacy);
        assertEquals(privacy, abilityBuilder.getPrivacy(), "Expected privacy does not match with actual privacy");
    }

    @Test
    public void testPrivacyMethodWithUserPrivacy() {
        Privacy privacy = Privacy.USER;
        abilityBuilder.privacy(privacy);
        assertEquals(privacy, abilityBuilder.getPrivacy(), "Expected privacy does not match with actual privacy");
    }

    @Test
    public void testPrivacyMethodWithNullPrivacy() {
        assertThrows(NullPointerException.class, () -> abilityBuilder.privacy(null), "Expected NullPointerException to be thrown");
    }
}
