// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Ability_enableStats_34e59ed22e_Test {
    private AbilityBuilder abilityBuilder;

    @BeforeEach
    void setUp() {
        abilityBuilder = new AbilityBuilder();
    }

    @Test
    void testEnableStatsSuccess() {
        abilityBuilder = abilityBuilder.enableStats();
        assertTrue(abilityBuilder.isStatsEnabled());
    }

    @Test
    void testEnableStatsFailure() {
        assertFalse(abilityBuilder.isStatsEnabled());
    }
}
