// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;

public class Ability_statsEnabled_fb61976c57_Test {

    @InjectMocks
    private Ability ability;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        ability = new Ability();
    }

    @Test
    public void testStatsEnabledTrue() {
        ability.setStatsEnabled(true);
        assertTrue(ability.statsEnabled());
    }

    @Test
    public void testStatsEnabledFalse() {
        ability.setStatsEnabled(false);
        assertFalse(ability.statsEnabled());
    }
}
