// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Ability_tokens_b60600a1c8_Test {

    private Ability ability;

    @BeforeEach
    public void setUp() {
        ability = new Ability();
    }

    @Test
    public void testTokensWithPositiveArgNum() {
        int argNum = 5;
        ability.setArgNum(argNum);
        assertEquals(argNum, ability.tokens(), "Expected tokens to return the same value as argNum");
    }

    @Test
    public void testTokensWithZeroArgNum() {
        int argNum = 0;
        ability.setArgNum(argNum);
        assertEquals(argNum, ability.tokens(), "Expected tokens to return the same value as argNum");
    }
}
