// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.telegram.abilitybots.api.bot.BaseAbilityBot;
import org.telegram.telegrambots.meta.api.objects.Update;
import java.util.Arrays;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Predicate;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Ability_flag_802d212bdb_Test {
    private AbilityBuilder abilityBuilder;
    private Predicate<Update> predicateMock;

    @BeforeEach
    public void setup() {
        abilityBuilder = new AbilityBuilder();
        predicateMock = mock(Predicate.class);  // Mocking Predicate
    }

    @Test
    public void testFlagMethodWithValidFlags() {
        // Test with valid flags
        AbilityBuilder result = abilityBuilder.flag(predicateMock);
        assertEquals(abilityBuilder, result, "Expected and actual objects should be same");
    }

    @Test
    public void testFlagMethodWithNullFlags() {
        // Test with null flags, it should throw NullPointerException
        assertThrows(NullPointerException.class, () -> abilityBuilder.flag(null));
    }
}
