// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Ability_privacy_0994bdbb80_Test {

    @Mock
    private Ability ability;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testPrivacyMethod() {
        Privacy expectedPrivacy = Privacy.PRIVATE;
        when(ability.privacy()).thenReturn(expectedPrivacy);

        Privacy actualPrivacy = ability.privacy();
        assertEquals(expectedPrivacy, actualPrivacy, "Expected privacy does not match actual privacy");
    }

    @Test
    public void testPrivacyMethodWithNull() {
        when(ability.privacy()).thenReturn(null);

        Privacy actualPrivacy = ability.privacy();
        assertEquals(null, actualPrivacy, "Expected privacy does not match actual privacy");
    }
}
