// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Ability_name_a39cfef4a9_Test {

    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setup() {
        abilityBuilder = Mockito.mock(AbilityBuilder.class);
    }

    @Test
    public void testNameMethod_WithValidName() {
        String testName = "testName";
        Mockito.when(abilityBuilder.name(testName)).thenReturn(abilityBuilder);

        AbilityBuilder result = abilityBuilder.name(testName);

        assertEquals(abilityBuilder, result);
        Mockito.verify(abilityBuilder).name(testName);
    }

    @Test
    public void testNameMethod_WithEmptyName() {
        String testName = "";
        Mockito.when(abilityBuilder.name(testName)).thenReturn(abilityBuilder);

        AbilityBuilder result = abilityBuilder.name(testName);

        assertEquals(abilityBuilder, result);
        Mockito.verify(abilityBuilder).name(testName);
    }
}
