// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.bot.AbilityBot;
import org.telegram.abilitybots.api.objects.Ability.AbilityBuilder;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.verify;

public class Ability_post_a08aee9fcd_Test {

    @Mock
    private Consumer<MessageContext> postAction;

    private AbilityBuilder abilityBuilder;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
        abilityBuilder = new AbilityBuilder();
    }

    @Test
    public void testPostActionNotNull() {
        abilityBuilder.post(postAction);
        assertNotNull(abilityBuilder.postAction);
    }

    @Test
    public void testPostActionCalled() {
        abilityBuilder.post(postAction);
        verify(postAction).accept(any(MessageContext.class));
    }
}
