// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Ability_locality_d50a79ba94_Test {

    private Locality localityMock;
    private Ability ability;

    @BeforeEach
    public void setup() {
        localityMock = mock(Locality.class);
        ability = new Ability();
        ability.setLocality(localityMock);
    }

    @Test
    public void testLocalityNotNull() {
        assertNotNull(ability.locality(), "Locality should not be null");
    }

    @Test
    public void testLocality() {
        when(localityMock.toString()).thenReturn("Mocked Locality");
        assertEquals("Mocked Locality", ability.locality().toString(), "Locality should match expected value");
    }
}
