// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Ability_setStatsEnabled_c445ddef6b_Test {

    private AbilityBuilder abilityBuilder;

    @BeforeEach
    public void setup() {
        abilityBuilder = new AbilityBuilder();
    }

    @Test
    public void testSetStatsEnabled_true() {
        abilityBuilder.setStatsEnabled(true);
        // TODO: Replace the assertion value with the actual value
        assertEquals(true, abilityBuilder.isStatsEnabled());
    }

    @Test
    public void testSetStatsEnabled_false() {
        abilityBuilder.setStatsEnabled(false);
        // TODO: Replace the assertion value with the actual value
        assertEquals(false, abilityBuilder.isStatsEnabled());
    }
}
