// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.doNothing;

public class Ability_reply_97b51f75fd_Test {

    private AbilityBuilder abilityBuilder;
    private Reply reply;

    @BeforeEach
    public void setUp() {
        abilityBuilder = Mockito.mock(AbilityBuilder.class);
        reply = Mockito.mock(Reply.class);
    }

    @Test
    public void testReplySuccess() {
        doNothing().when(abilityBuilder).reply(reply);
        assertEquals(abilityBuilder, abilityBuilder.reply(reply));
    }

    @Test
    public void testReplyFailure() {
        doNothing().when(abilityBuilder).reply(null);
        assertThrows(NullPointerException.class, () -> abilityBuilder.reply(null));
    }
}
