// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.telegrambots.meta.api.objects.Update;
import java.util.function.Predicate;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

public class Flag_test_c1a90a4744_Test {

    @Mock
    private Predicate<Update> predicate;

    private Flag_test_c1a90a4744_Test flagTest;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        flagTest = new Flag_test_c1a90a4744_Test();
    }

    @Test
    public void testShouldReturnFalseWhenUpdateIsNull() {
        assertFalse(flagTest.test(null));
    }

    @Test
    public void testShouldReturnFalseWhenPredicateFails() {
        Update update = new Update();
        when(predicate.test(any(Update.class))).thenReturn(false);

        assertFalse(flagTest.test(update));
    }

    @Test
    public void testShouldReturnTrueWhenPredicatePasses() {
        Update update = new Update();
        when(predicate.test(any(Update.class))).thenReturn(true);

        assertTrue(flagTest.test(update));
    }
}
