// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.telegram.abilitybots.api.bot.BaseAbilityBot;
import org.telegram.telegrambots.meta.api.objects.Update;
import org.telegram.telegrambots.meta.api.objects.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class MessageContext_MessageContext_f2b68842a2_Test {

    private MessageContext messageContext;
    private Update update;
    private User user;
    private Long chatId;
    private BaseAbilityBot bot;
    private String[] arguments;

    @BeforeEach
    public void setUp() {
        update = Mockito.mock(Update.class);
        user = Mockito.mock(User.class);
        chatId = 1234L;
        bot = Mockito.mock(BaseAbilityBot.class);
        arguments = new String[]{"arg1", "arg2"};
        messageContext = new MessageContext(update, user, chatId, bot, arguments);
    }

    @Test
    public void testMessageContextWithValidInputs() {
        assertEquals(user, messageContext.getUser());
        assertEquals(chatId, messageContext.getChatId());
        assertEquals(update, messageContext.getUpdate());
        assertEquals(bot, messageContext.getBot());
        assertEquals(Arrays.toString(arguments), Arrays.toString(messageContext.getArguments()));
    }

    @Test
    public void testMessageContextWithNullInputs() {
        assertThrows(NullPointerException.class, () -> new MessageContext(null, null, null, null, null));
    }
}
