// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.telegram.abilitybots.api.bot.BaseAbilityBot;
import org.telegram.telegrambots.meta.api.objects.Update;
import org.telegram.telegrambots.meta.api.objects.User;
import java.util.Arrays;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class MessageContext_bot_8f70e3b98b_Test {

    private BaseAbilityBot bot;

    @BeforeEach
    public void setup() {
        bot = Mockito.mock(BaseAbilityBot.class);
    }

    @Test
    public void testBotMethodReturnsCorrectBot() {
        MessageContext context = new MessageContext(bot);
        BaseAbilityBot returnedBot = context.bot();
        assertEquals(bot, returnedBot, "Returned bot should be the same as the bot used for setup");
    }

    @Test
    public void testBotMethodWithDifferentBot() {
        BaseAbilityBot differentBot = Mockito.mock(BaseAbilityBot.class);
        MessageContext context = new MessageContext(differentBot);
        BaseAbilityBot returnedBot = context.bot();
        assertEquals(differentBot, returnedBot, "Returned bot should be the same as the bot used for setup");
    }
}
