// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class MessageContext_chatId_1b61e4cb8a_Test {

    @InjectMocks
    private MessageContext messageContext;

    @Mock
    private Update update;

    @Mock
    private User user;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testChatId_Success() {
        when(update.getMessage().getChatId()).thenReturn(12345L);
        Long expectedChatId = 12345L;
        Long actualChatId = messageContext.chatId();
        assertEquals(expectedChatId, actualChatId);
    }

    @Test
    public void testChatId_Failure() {
        when(update.getMessage().getChatId()).thenReturn(12345L);
        Long unexpectedChatId = 54321L;
        Long actualChatId = messageContext.chatId();
        assertNotEquals(unexpectedChatId, actualChatId);
    }
}
