// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.objects;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;

public class MessageContext_arguments_a3b2e5b7f3_Test {

    private MessageContext messageContext;

    @BeforeEach
    public void setUp() {
        messageContext = new MessageContext();
    }

    @Test
    public void testArgumentsWhenArgumentsAreSet() {
        String[] expectedArguments = {"arg1", "arg2", "arg3"};
        messageContext.setArguments(expectedArguments);
        String[] actualArguments = messageContext.arguments();
        assertArrayEquals(expectedArguments, actualArguments);
    }

    @Test
    public void testArgumentsWhenArgumentsAreNotSet() {
        String[] expectedArguments = {};
        String[] actualArguments = messageContext.arguments();
        assertArrayEquals(expectedArguments, actualArguments);
    }
}
