// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.db.DBContext;
import org.telegram.abilitybots.api.toggle.AbilityToggle;
import org.telegram.abilitybots.api.toggle.DefaultToggle;
import org.telegram.telegrambots.bots.DefaultBotOptions;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class AbilityWebhookBot_AbilityWebhookBot_492563dfd1_Test {

    @Mock
    private DBContext dbContext;
    @Mock
    private AbilityToggle abilityToggle;
    @Mock
    private DefaultBotOptions defaultBotOptions;

    private AbilityWebhookBot abilityWebhookBot;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        abilityWebhookBot = new AbilityWebhookBot("testBotToken", "testBotUsername", "testBotPath", abilityToggle, defaultBotOptions);
    }

    @Test
    public void testAbilityWebhookBot_withValidParameters() {
        assertNotNull(abilityWebhookBot);
        assertEquals("testBotToken", abilityWebhookBot.getBotToken());
        assertEquals("testBotUsername", abilityWebhookBot.getBotUsername());
        assertEquals("testBotPath", abilityWebhookBot.getBotPath());
    }

    @Test
    public void testAbilityWebhookBot_withNullParameters() {
        assertThrows(NullPointerException.class, () -> {
            new AbilityWebhookBot(null, null, null, null, null);
        });
    }
}
