// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class AbilityWebhookBot_getBotPath_3a0656bd6d_Test {

    @InjectMocks
    private AbilityWebhookBot abilityWebhookBot;

    @Mock
    private String botPath;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetBotPathSuccess() {
        String expectedBotPath = "testBotPath";
        Mockito.when(botPath.getBotPath()).thenReturn(expectedBotPath);
        String actualBotPath = abilityWebhookBot.getBotPath();
        Assertions.assertEquals(expectedBotPath, actualBotPath);
    }

    @Test
    public void testGetBotPathFailure() {
        String expectedBotPath = null;
        Mockito.when(botPath.getBotPath()).thenReturn(expectedBotPath);
        String actualBotPath = abilityWebhookBot.getBotPath();
        Assertions.assertEquals(expectedBotPath, actualBotPath);
    }
}
