// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.db.DBContext;
import org.telegram.abilitybots.api.toggle.AbilityToggle;
import org.telegram.abilitybots.api.toggle.DefaultToggle;
import org.telegram.telegrambots.bots.DefaultBotOptions;
import org.telegram.telegrambots.bots.TelegramWebhookBot;
import org.telegram.telegrambots.meta.api.methods.BotApiMethod;
import org.telegram.telegrambots.meta.api.methods.updates.SetWebhook;
import org.telegram.telegrambots.meta.api.objects.Update;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.meta.generics.WebhookBot;
import org.telegram.telegrambots.util.WebhookUtils;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

public class AbilityWebhookBot_AbilityWebhookBot_8cc6d9f6b1_Test {

    @Mock
    private DefaultBotOptions botOptions;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testAbilityWebhookBot_Success() {
        String botToken = "botToken";
        String botUsername = "botUsername";
        String botPath = "botPath";

        AbilityWebhookBot bot = new AbilityWebhookBot(botToken, botUsername, botPath, botOptions);

        assertEquals(botToken, bot.getBotToken());
        assertEquals(botUsername, bot.getBotUsername());
        assertEquals(botPath, bot.getBotPath());
    }

    @Test
    public void testAbilityWebhookBot_Failure() {
        String botToken = null;
        String botUsername = null;
        String botPath = null;

        assertThrows(NullPointerException.class, () -> {
            new AbilityWebhookBot(botToken, botUsername, botPath, botOptions);
        });
    }
}
