// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.telegrambots.meta.api.methods.updates.SetWebhook;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.util.WebhookUtils;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

public class AbilityWebhookBot_setWebhook_a27446f798_Test {

    @Mock
    private AbilityWebhookBot abilityWebhookBot;

    @Mock
    private SetWebhook setWebhook;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetWebhook_Success() throws TelegramApiException {
        // Arrange
        when(WebhookUtils.setWebhook(abilityWebhookBot, abilityWebhookBot, setWebhook)).thenReturn(true);

        // Act
        abilityWebhookBot.setWebhook(setWebhook);

        // Assert
        verify(WebhookUtils).setWebhook(abilityWebhookBot, abilityWebhookBot, setWebhook);
    }

    @Test
    public void testSetWebhook_Failure() throws TelegramApiException {
        // Arrange
        when(WebhookUtils.setWebhook(abilityWebhookBot, abilityWebhookBot, setWebhook)).thenThrow(TelegramApiException.class);

        // Act & Assert
        assertThrows(TelegramApiException.class, () -> abilityWebhookBot.setWebhook(setWebhook));
    }
}
