// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.toggle.AbilityToggle;
import org.telegram.abilitybots.api.toggle.DefaultToggle;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class AbilityWebhookBot_AbilityWebhookBot_f6fd340373_Test {

    @Mock
    private AbilityToggle toggle;

    private AbilityWebhookBot abilityWebhookBot;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        when(toggle.name()).thenReturn("TestToggle");
    }

    @Test
    public void testAbilityWebhookBot_Success() {
        abilityWebhookBot = new AbilityWebhookBot("testToken", "testUsername", "testPath", toggle);
        assertEquals("testToken", abilityWebhookBot.getBotToken());
        assertEquals("testUsername", abilityWebhookBot.getBotUsername());
        assertEquals("testPath", abilityWebhookBot.getBotPath());
        assertEquals("TestToggle", abilityWebhookBot.getToggle().name());
    }

    @Test
    public void testAbilityWebhookBot_Failure() {
        try {
            abilityWebhookBot = new AbilityWebhookBot("", "", "", null);
        } catch (IllegalArgumentException e) {
            assertEquals("Bot token and username must not be empty", e.getMessage());
        }
    }
}
