// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

public class BaseAbilityBot_isCreator_f84117a0dc_Test {
    
    @Mock
    private BaseAbilityBot baseAbilityBot;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsCreator_True() {
        long creatorId = 12345L;
        Mockito.when(baseAbilityBot.creatorId()).thenReturn(creatorId);
        Assert.assertTrue(baseAbilityBot.isCreator(creatorId));
    }

    @Test
    public void testIsCreator_False() {
        long creatorId = 12345L;
        Mockito.when(baseAbilityBot.creatorId()).thenReturn(creatorId);
        Assert.assertFalse(baseAbilityBot.isCreator(67890L));
    }
}
