// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.telegram.abilitybots.api.objects.Ability;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@ExtendWith(MockitoExtension.class)
public class BaseAbilityBot_abilities_972cf986b0_Test {

    private Map<String, Ability> abilities;

    @BeforeEach
    public void setup() {
        abilities = new HashMap<>();
        abilities.put("ability1", new Ability());
        abilities.put("ability2", new Ability());
    }

    @Test
    public void testAbilities() {
        Map<String, Ability> expectedAbilities = new HashMap<>();
        expectedAbilities.put("ability1", new Ability());
        expectedAbilities.put("ability2", new Ability());

        assertEquals(expectedAbilities, abilities);
    }

    @Test
    public void testAbilitiesWhenEmpty() {
        abilities.clear();

        assertTrue(abilities.isEmpty());
    }
}
