// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.sender.SilentSender;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class BaseAbilityBot_silent_f323ab8a5f_Test {

    @Test
    public void testSilentSuccess() {
        SilentSender mockSilentSender = Mockito.mock(SilentSender.class);
        BaseAbilityBot baseAbilityBot = new BaseAbilityBot(mockSilentSender);

        SilentSender result = baseAbilityBot.silent();

        assertEquals(mockSilentSender, result, "Expected and actual SilentSender should be same");
    }

    @Test
    public void testSilentFailure() {
        BaseAbilityBot baseAbilityBot = new BaseAbilityBot(null);

        assertThrows(NullPointerException.class, baseAbilityBot::silent, "Expected NullPointerException");
    }
}
