// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.util.AbilityExtension;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class BaseAbilityBot_addExtensions_f7261a63b4_Test {

    private BaseAbilityBot bot;
    private AbilityExtension extension1;
    private AbilityExtension extension2;

    @BeforeEach
    public void setUp() {
        bot = Mockito.mock(BaseAbilityBot.class);
        extension1 = Mockito.mock(AbilityExtension.class);
        extension2 = Mockito.mock(AbilityExtension.class);
    }

    @Test
    public void testAddExtensions() {
        Collection<AbilityExtension> extensions = Arrays.asList(extension1, extension2);
        when(bot.getExtensions()).thenReturn(extensions);
        bot.addExtensions(extensions);
        assertEquals(2, bot.getExtensions().size());
    }

    @Test
    public void testAddEmptyExtensions() {
        Collection<AbilityExtension> extensions = Collections.emptyList();
        when(bot.getExtensions()).thenReturn(extensions);
        bot.addExtensions(extensions);
        assertEquals(0, bot.getExtensions().size());
    }

    @Test
    public void testAddNullExtensions() {
        Collection<AbilityExtension> extensions = null;
        when(bot.getExtensions()).thenReturn(extensions);
        bot.addExtensions(extensions);
        assertEquals(0, bot.getExtensions().size());
    }
}
