// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.objects.ReplyCollection;

import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.*;

class BaseAbilityBot_returnReplyCollection_d82f6226f4_Test {

    @Test
    void testReturnReplyCollectionSuccess() throws NoSuchMethodException {
        Object obj = new Object() {
            @SuppressWarnings("unused")
            ReplyCollection method() {
                return new ReplyCollection();
            }
        };
        Method method = obj.getClass().getDeclaredMethod("method");

        Function<Method, ReplyCollection> function = BaseAbilityBot.returnReplyCollection(obj);
        ReplyCollection result = function.apply(method);

        assertNotNull(result);
        assertTrue(result instanceof ReplyCollection);
    }

    @Test
    void testReturnReplyCollectionFailure() throws NoSuchMethodException {
        Object obj = Mockito.mock(Object.class);
        Method method = obj.getClass().getDeclaredMethod("method");

        Function<Method, ReplyCollection> function = BaseAbilityBot.returnReplyCollection(obj);

        Exception exception = assertThrows(RuntimeException.class, () -> {
            function.apply(method);
        });

        String expectedMessage = "Could not add Reply Collection";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}
