// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class BaseAbilityBot_getBotUsername_bcfa803a56_Test {

    @InjectMocks
    private BaseAbilityBot baseAbilityBot;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetBotUsername_whenUsernameIsSet() {
        String expectedUsername = "TestBot";
        // TODO: Set the bot username value
        baseAbilityBot.botUsername = expectedUsername;

        String actualUsername = baseAbilityBot.getBotUsername();

        assertEquals(expectedUsername, actualUsername, "Bot username does not match the expected value");
    }

    @Test
    public void testGetBotUsername_whenUsernameIsNotSet() {
        String expectedUsername = null;
        // TODO: Ensure the bot username value is not set

        String actualUsername = baseAbilityBot.getBotUsername();

        assertNull(actualUsername, "Bot username is supposed to be null");
    }
}
