// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class BaseAbilityBot_getCommandRegexSplit_072e98173d_Test {

    @Test
    public void testGetCommandRegexSplit_Success() {
        BaseAbilityBot bot = new BaseAbilityBot();
        String expectedOutput = " ";
        assertEquals(expectedOutput, bot.getCommandRegexSplit(), "The expected output should be a single space");
    }

    @Test
    public void testGetCommandRegexSplit_Failure() {
        BaseAbilityBot bot = new BaseAbilityBot();
        String unexpectedOutput = "  ";
        assertNotEquals(unexpectedOutput, bot.getCommandRegexSplit(), "The output should not be two spaces");
    }
}
