// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.objects.Reply;

import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class BaseAbilityBot_returnReply_f4aa892813_Test {

    private static class TestObject {
        public Reply testMethod() {
            return new Reply();
        }

        public Reply exceptionMethod() throws Exception {
            throw new Exception("Test Exception");
        }
    }

    @Test
    public void testReturnReplySuccess() throws NoSuchMethodException {
        TestObject testObject = new TestObject();
        Method method = TestObject.class.getMethod("testMethod");
        Reply expectedReply = new Reply();

        Function<? super Method, Reply> returnReply = BaseAbilityBot.returnReply(testObject);
        Reply actualReply = returnReply.apply(method);

        assertEquals(expectedReply, actualReply);
    }

    @Test
    public void testReturnReplyFailure() throws NoSuchMethodException {
        TestObject testObject = new TestObject();
        Method method = TestObject.class.getMethod("exceptionMethod");

        Function<? super Method, Reply> returnReply = BaseAbilityBot.returnReply(testObject);

        Exception exception = assertThrows(RuntimeException.class, () -> {
            returnReply.apply(method);
        });

        String expectedMessage = "Could not add reply";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}
