// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.telegram.abilitybots.api.db.DBContext;

import java.util.HashMap;
import java.util.Map;

public class BaseAbilityBot_userIds_62756bbf1f_Test {
    private BaseAbilityBot baseAbilityBot;
    private DBContext db;

    @BeforeEach
    public void setUp() {
        db = mock(DBContext.class);
        baseAbilityBot = new BaseAbilityBot("testBot", "testToken") {
            @Override
            public int creatorId() {
                return 123456789;
            }
        };
        baseAbilityBot.setDB(db);
    }

    @Test
    public void testUserIds() {
        Map<String, Long> expected = new HashMap<>();
        expected.put("user1", 1L);
        expected.put("user2", 2L);
        when(db.getMap(BaseAbilityBot.USER_ID)).thenReturn(expected);
        Map<String, Long> actual = baseAbilityBot.userIds();
        assertEquals(expected, actual);
    }

    @Test
    public void testUserIdsEmpty() {
        Map<String, Long> expected = new HashMap<>();
        when(db.getMap(BaseAbilityBot.USER_ID)).thenReturn(expected);
        Map<String, Long> actual = baseAbilityBot.userIds();
        assertEquals(expected, actual);
    }
}
