// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.telegrambots.meta.api.objects.Update;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.mockito.Mockito.when;

public class BaseAbilityBot_checkGlobalFlags_8ab5c0eaa6_Test {

    @Mock
    private Update update;

    private BaseAbilityBot bot;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        bot = new BaseAbilityBot("TOKEN", "BOT_NAME");
    }

    @Test
    public void testCheckGlobalFlags_WithValidUpdate() {
        when(update.hasMessage()).thenReturn(true);
        assertTrue(bot.checkGlobalFlags(update));
    }

    @Test
    public void testCheckGlobalFlags_WithInvalidUpdate() {
        when(update.hasMessage()).thenReturn(false);
        assertFalse(bot.checkGlobalFlags(update));
    }

}
