// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.db.DBContext;
import org.telegram.abilitybots.api.sender.DefaultSender;
import org.telegram.abilitybots.api.sender.SilentSender;
import org.telegram.abilitybots.api.toggle.AbilityToggle;
import org.telegram.telegrambots.bots.DefaultBotOptions;

public class BaseAbilityBot_BaseAbilityBot_68b58aa274_Test {

    private String botToken;
    private String botUsername;
    private DBContext db;
    private AbilityToggle toggle;
    private DefaultBotOptions botOptions;

    @BeforeEach
    public void setUp() {
        botToken = "testBotToken";
        botUsername = "testBotUsername";
        db = Mockito.mock(DBContext.class);
        toggle = Mockito.mock(AbilityToggle.class);
        botOptions = Mockito.mock(DefaultBotOptions.class);
    }

    @Test
    public void testBaseAbilityBotConstructor() {
        BaseAbilityBot bot = new BaseAbilityBot(botToken, botUsername, db, toggle, botOptions);

        Assertions.assertEquals(botToken, bot.getBotToken());
        Assertions.assertEquals(botUsername, bot.getBotUsername());
        Assertions.assertEquals(db, bot.getDBContext());
        Assertions.assertEquals(toggle, bot.getAbilityToggle());
        Assertions.assertTrue(bot.getSender() instanceof DefaultSender);
        Assertions.assertTrue(bot.getSilent() instanceof SilentSender);
    }

    @Test
    public void testBaseAbilityBotConstructor_NullBotToken() {
        Assertions.assertThrows(NullPointerException.class, () -> new BaseAbilityBot(null, botUsername, db, toggle, botOptions));
    }

    @Test
    public void testBaseAbilityBotConstructor_NullBotUsername() {
        Assertions.assertThrows(NullPointerException.class, () -> new BaseAbilityBot(botToken, null, db, toggle, botOptions));
    }

    @Test
    public void testBaseAbilityBotConstructor_NullDBContext() {
        Assertions.assertThrows(NullPointerException.class, () -> new BaseAbilityBot(botToken, botUsername, null, toggle, botOptions));
    }

    @Test
    public void testBaseAbilityBotConstructor_NullAbilityToggle() {
        Assertions.assertThrows(NullPointerException.class, () -> new BaseAbilityBot(botToken, botUsername, db, null, botOptions));
    }

    @Test
    public void testBaseAbilityBotConstructor_NullBotOptions() {
        Assertions.assertThrows(NullPointerException.class, () -> new BaseAbilityBot(botToken, botUsername, db, toggle, null));
    }
}
