// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.util.AbilityExtension;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class BaseAbilityBot_addExtension_80b9abb3d7_Test {

    private BaseAbilityBot bot;
    private Set<AbilityExtension> extensions;

    @BeforeEach
    void setUp() {
        bot = Mockito.mock(BaseAbilityBot.class);
        extensions = new HashSet<>();
        Mockito.doCallRealMethod().when(bot).addExtension(Mockito.any());
        Mockito.when(bot.getExtensions()).thenReturn(extensions);
    }

    @Test
    void testAddExtension() {
        AbilityExtension extension = Mockito.mock(AbilityExtension.class);
        bot.addExtension(extension);
        assertTrue(extensions.contains(extension));
    }

    @Test
    void testAddExtension_Null() {
        Exception exception = assertThrows(NullPointerException.class, () -> {
            bot.addExtension(null);
        });
        String expectedMessage = "Extension cannot be null";
        String actualMessage = exception.getMessage();
        assertTrue(actualMessage.contains(expectedMessage));
    }
}
