// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class BaseAbilityBot_allowContinuousText_93ea86877d_Test {

    @Test
    public void testAllowContinuousText_whenCalled_returnsFalse() {
        // Arrange
        BaseAbilityBot bot = new BaseAbilityBot();

        // Act
        boolean result = bot.allowContinuousText();

        // Assert
        Assertions.assertFalse(result, "Expected allowContinuousText() to return false");
    }

    @Test
    public void testAllowContinuousText_whenCalledMultipleTimes_returnsFalse() {
        // Arrange
        BaseAbilityBot bot = new BaseAbilityBot();

        // Act
        boolean result1 = bot.allowContinuousText();
        boolean result2 = bot.allowContinuousText();
        boolean result3 = bot.allowContinuousText();

        // Assert
        Assertions.assertFalse(result1, "Expected allowContinuousText() to return false on first call");
        Assertions.assertFalse(result2, "Expected allowContinuousText() to return false on second call");
        Assertions.assertFalse(result3, "Expected allowContinuousText() to return false on third call");
    }
}
