// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.util.AbilityExtension;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class BaseAbilityBot_addExtensions_f63e4279a8_Test {

    private BaseAbilityBot bot;
    private List<AbilityExtension> extensions;

    @BeforeEach
    public void setUp() {
        bot = Mockito.mock(BaseAbilityBot.class);
        extensions = new ArrayList<>();
        Mockito.doCallRealMethod().when(bot).addExtensions(Mockito.any());
        Mockito.when(bot.getExtensions()).thenReturn(extensions);
    }

    @Test
    public void testAddExtensions_Successful() {
        AbilityExtension extension1 = Mockito.mock(AbilityExtension.class);
        AbilityExtension extension2 = Mockito.mock(AbilityExtension.class);
        
        bot.addExtensions(extension1, extension2);
        
        assertEquals(2, extensions.size());
        assertEquals(extension1, extensions.get(0));
        assertEquals(extension2, extensions.get(1));
    }

    @Test
    public void testAddExtensions_Null() {
        assertThrows(NullPointerException.class, () -> bot.addExtensions((AbilityExtension) null));
    }
}
