// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.telegrambots.meta.api.objects.Update;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class BaseAbilityBot_isGroupAdmin_9db33820ad_Test {

    @InjectMocks
    private BaseAbilityBot baseAbilityBot;

    @Mock
    private Update update;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsGroupAdmin_Success() {
        long id = 12345L;
        when(baseAbilityBot.getChatId(update)).thenReturn(id);
        when(baseAbilityBot.isGroupAdmin(anyLong(), eq(id))).thenReturn(true);

        boolean result = baseAbilityBot.isGroupAdmin(update, id);

        assertTrue(result);
        verify(baseAbilityBot, times(1)).isGroupAdmin(anyLong(), eq(id));
    }

    @Test
    public void testIsGroupAdmin_Failure() {
        long id = 12345L;
        when(baseAbilityBot.getChatId(update)).thenReturn(id);
        when(baseAbilityBot.isGroupAdmin(anyLong(), eq(id))).thenReturn(false);

        boolean result = baseAbilityBot.isGroupAdmin(update, id);

        assertFalse(result);
        verify(baseAbilityBot, times(1)).isGroupAdmin(anyLong(), eq(id));
    }
}
