// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

public class BaseAbilityBot_isAdmin_85472e53b8_Test {

    @InjectMocks
    private BaseAbilityBot baseAbilityBot;

    @Mock
    private Set<Long> admins;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsAdmin_withAdminId_shouldReturnTrue() {
        // Arrange
        long adminId = 12345;
        Set<Long> adminSet = new HashSet<>();
        adminSet.add(adminId);
        when(admins.contains(adminId)).thenReturn(true);

        // Act
        boolean result = baseAbilityBot.isAdmin(adminId);

        // Assert
        assertTrue(result, "Expected true when the id is of an admin");
    }

    @Test
    public void testIsAdmin_withNonAdminId_shouldReturnFalse() {
        // Arrange
        long nonAdminId = 67890;
        when(admins.contains(nonAdminId)).thenReturn(false);

        // Act
        boolean result = baseAbilityBot.isAdmin(nonAdminId);

        // Assert
        assertFalse(result, "Expected false when the id is not of an admin");
    }
}
