// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import java.lang.reflect.Method;
import java.util.function.Predicate;

public class BaseAbilityBot_checkReturnType_514b955223_Test {

    @Test
    public void testCheckReturnType_ValidReturnType() throws NoSuchMethodException {
        Predicate<Method> predicate = BaseAbilityBot.checkReturnType(String.class);
        Method method = DummyClass.class.getDeclaredMethod("validMethod");
        Assertions.assertTrue(predicate.test(method));
    }

    @Test
    public void testCheckReturnType_InvalidReturnType() throws NoSuchMethodException {
        Predicate<Method> predicate = BaseAbilityBot.checkReturnType(Integer.class);
        Method method = DummyClass.class.getDeclaredMethod("validMethod");
        Assertions.assertFalse(predicate.test(method));
    }

    @Test
    public void testCheckReturnType_NullMethod() {
        Predicate<Method> predicate = BaseAbilityBot.checkReturnType(Integer.class);
        Assertions.assertThrows(NullPointerException.class, () -> predicate.test(null));
    }

    private static class DummyClass {
        private String validMethod() {
            return "Hello World";
        }
    }
}
