// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;

public class BaseAbilityBot_onRegister_db814034aa_Test {

    @InjectMocks
    BaseAbilityBot baseAbilityBot;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testOnRegister() {
        baseAbilityBot.onRegister();
        verify(baseAbilityBot, times(1)).registerAbilities();
        verify(baseAbilityBot, times(1)).initStats();
    }

    @Test
    public void testOnRegisterFailure() {
        doThrow(new RuntimeException()).when(baseAbilityBot).registerAbilities();
        Assertions.assertThrows(RuntimeException.class, () -> baseAbilityBot.onRegister());
    }
}
