// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.HashSet;
import java.util.Set;

public class BaseAbilityBot_admins_ee5003ed7b_Test {

    @Mock
    private DBContext db;

    private BaseAbilityBot baseAbilityBot;

    private static final String ADMINS = "admins";

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        baseAbilityBot = new BaseAbilityBot("botToken", "botUsername", db);
    }

    @Test
    public void testAdminsWhenAdminsExist() {
        Set<Long> expectedAdmins = new HashSet<>();
        expectedAdmins.add(123456789L);
        expectedAdmins.add(987654321L);

        when(db.getSet(ADMINS)).thenReturn(expectedAdmins);

        Set<Long> actualAdmins = baseAbilityBot.admins();

        assertEquals(expectedAdmins, actualAdmins);
    }

    @Test
    public void testAdminsWhenNoAdminsExist() {
        Set<Long> expectedAdmins = new HashSet<>();

        when(db.getSet(ADMINS)).thenReturn(expectedAdmins);

        Set<Long> actualAdmins = baseAbilityBot.admins();

        assertEquals(expectedAdmins, actualAdmins);
    }
}
