// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.db.DBContext;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class BaseAbilityBot_blacklist_2ccf775d86_Test {

    @Mock
    private DBContext db;

    private BaseAbilityBot baseAbilityBot;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
        baseAbilityBot = new BaseAbilityBot(db);
    }

    @Test
    public void testBlacklist() {
        Set<Long> expected = new HashSet<>();
        expected.add(12345L);
        expected.add(67890L);

        when(db.getSet(BaseAbilityBot.BLACKLIST)).thenReturn(expected);

        Set<Long> actual = baseAbilityBot.blacklist();

        assertEquals(expected, actual);
    }

    @Test
    public void testBlacklistWhenNoBlacklist() {
        Set<Long> expected = new HashSet<>();

        when(db.getSet(BaseAbilityBot.BLACKLIST)).thenReturn(expected);

        Set<Long> actual = baseAbilityBot.blacklist();

        assertEquals(expected, actual);
    }
}
