// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.telegrambots.meta.api.objects.Update;

import static org.mockito.Mockito.*;

public class BaseAbilityBot_onUpdateReceived_fb2cc743d7_Test {

    @Mock
    private BaseAbilityBot baseAbilityBot;

    @Mock
    private Update update;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testOnUpdateReceived_success() {
        doNothing().when(baseAbilityBot).onUpdateReceived(any(Update.class));
        baseAbilityBot.onUpdateReceived(update);
        verify(baseAbilityBot, times(1)).onUpdateReceived(update);
    }

    @Test
    public void testOnUpdateReceived_failure() {
        doThrow(new RuntimeException()).when(baseAbilityBot).onUpdateReceived(any(Update.class));
        try {
            baseAbilityBot.onUpdateReceived(update);
        } catch (Exception e) {
            verify(baseAbilityBot, times(1)).onUpdateReceived(update);
        }
    }

    @Test
    public void testOnUpdateReceived_processingTime() {
        doAnswer(invocation -> {
            long millisStarted = System.currentTimeMillis();
            // Simulate processing time
            Thread.sleep(100);
            long processingTime = System.currentTimeMillis() - millisStarted;
            return processingTime;
        }).when(baseAbilityBot).onUpdateReceived(any(Update.class));
        baseAbilityBot.onUpdateReceived(update);
        verify(baseAbilityBot, times(1)).onUpdateReceived(update);
    }
}
