// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.sender.MessageSender;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class BaseAbilityBot_sender_f554bb1c70_Test {
    private BaseAbilityBot baseAbilityBot;

    @Mock
    private MessageSender sender;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        baseAbilityBot = new BaseAbilityBot() {
            @Override
            public String getBotToken() {
                return null;
            }

            @Override
            public String getBotUsername() {
                return null;
            }
        };
        baseAbilityBot.setSender(sender);
    }

    @Test
    public void testSenderSuccess() {
        when(baseAbilityBot.sender()).thenReturn(sender);
        MessageSender result = baseAbilityBot.sender();
        assertEquals(sender, result);
    }

    @Test
    public void testSenderFailure() {
        when(baseAbilityBot.sender()).thenReturn(null);
        MessageSender result = baseAbilityBot.sender();
        assertEquals(null, result);
    }
}
