// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.telegram.abilitybots.api.objects.Stats;
import java.util.HashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class BaseAbilityBot_stats_d979af9d57_Test {

    BaseAbilityBot baseAbilityBot;
    Map<String, Stats> stats;

    @BeforeEach
    public void setup() {
        baseAbilityBot = Mockito.mock(BaseAbilityBot.class);
        stats = new HashMap<>();
        stats.put("testStat1", new Stats());
        stats.put("testStat2", new Stats());
    }

    @Test
    public void testStats_success() {
        when(baseAbilityBot.stats()).thenReturn(stats);

        Map<String, Stats> actualStats = baseAbilityBot.stats();

        assertEquals(stats, actualStats);
    }

    @Test
    public void testStats_empty() {
        stats.clear();
        when(baseAbilityBot.stats()).thenReturn(stats);

        Map<String, Stats> actualStats = baseAbilityBot.stats();

        assertEquals(stats, actualStats);
    }
}
