// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.telegram.abilitybots.api.objects.Reply;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import java.util.Arrays;
import java.util.List;

public class BaseAbilityBot_replies_611b9ba59a_Test {

    private BaseAbilityBot baseAbilityBot;

    @BeforeEach
    public void setUp() {
        baseAbilityBot = mock(BaseAbilityBot.class);
    }

    @Test
    public void testReplies_WhenRepliesNotEmpty() {
        List<Reply> expectedReplies = Arrays.asList(new Reply(), new Reply());
        when(baseAbilityBot.replies()).thenReturn(expectedReplies);

        List<Reply> actualReplies = baseAbilityBot.replies();

        assertEquals(expectedReplies, actualReplies);
    }

    @Test
    public void testReplies_WhenRepliesEmpty() {
        List<Reply> expectedReplies = Arrays.asList();
        when(baseAbilityBot.replies()).thenReturn(expectedReplies);

        List<Reply> actualReplies = baseAbilityBot.replies();

        assertEquals(expectedReplies, actualReplies);
    }
}
