// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.telegram.abilitybots.api.objects.Reply;

import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class BaseAbilityBot_updateReplyStats_27df2ffc07_Test {

    @Mock
    private BaseAbilityBot baseAbilityBot;

    @Mock
    private Reply reply;

    @Before
    public void setUp() {
        when(reply.name()).thenReturn("testReply");
    }

    @Test
    public void testUpdateReplyStats_WhenStatsEnabled() {
        when(reply.statsEnabled()).thenReturn(true);

        baseAbilityBot.updateReplyStats(reply);

        verify(baseAbilityBot, times(1)).updateStats(reply.name());
    }

    @Test
    public void testUpdateReplyStats_WhenStatsNotEnabled() {
        when(reply.statsEnabled()).thenReturn(false);

        baseAbilityBot.updateReplyStats(reply);

        verify(baseAbilityBot, times(0)).updateStats(reply.name());
    }
}
