// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.bot.BaseAbilityBot;
import org.telegram.abilitybots.api.bot.DefaultAbilities;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.*;

public class DefaultAbilities_DefaultAbilities_1e26b3ae3f_Test {

    @Mock
    BaseAbilityBot bot;

    DefaultAbilities defaultAbilities;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultAbilities = new DefaultAbilities(bot);
    }

    @Test
    public void testDefaultAbilities() {
        assertNotNull(defaultAbilities);
        verify(bot, times(1)).getDefaultAbilities();
    }

    @Test
    public void testDefaultAbilitiesWithNullBot() {
        Exception exception = null;
        try {
            new DefaultAbilities(null);
        } catch (Exception e) {
            exception = e;
        }
        assertNotNull(exception);
    }
}
