// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.objects.Ability;
import org.telegram.telegrambots.meta.api.objects.Update;
import org.telegram.telegrambots.meta.api.objects.User;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class DefaultAbilities_recoverDB_8e491a0a5b_Test {
    @Mock
    private DefaultAbilities defaultAbilities;
    @Mock
    private Update update;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRecoverDB_success() throws TelegramApiException {
        when(defaultAbilities.recoverDB()).thenReturn(Ability.builder().build());
        Ability result = defaultAbilities.recoverDB();
        assertEquals(Ability.builder().build(), result);
    }

    @Test
    public void testRecoverDB_failure() throws TelegramApiException {
        when(defaultAbilities.recoverDB()).thenThrow(TelegramApiException.class);
        try {
            defaultAbilities.recoverDB();
        } catch (TelegramApiException e) {
            assertEquals(TelegramApiException.class, e.getClass());
        }
    }
}
