// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.objects.User;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

public class DefaultAbilities_getUser_aacd31a6b3_Test {

    @Mock
    private DefaultAbilities bot;

    private Map<String, Long> mockUserIds;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
        mockUserIds = new HashMap<>();
        mockUserIds.put("john", 1L);
        mockUserIds.put("doe", 2L);
        when(bot.userIds()).thenReturn(mockUserIds);
    }

    @Test
    public void testGetUserSuccess() throws TelegramApiException {
        User expectedUser = new User();
        expectedUser.setId(1L);
        when(bot.getUser(1L)).thenReturn(expectedUser);

        User actualUser = bot.getUser("john");

        assertEquals(expectedUser, actualUser);
    }

    @Test
    public void testGetUserFailure() {
        assertThrows(IllegalStateException.class, () -> bot.getUser("nonexistentUser"));
    }
}
