// Test generated by RoostGPT for test telegramBot using AI Type Open AI and AI Model gpt-4

package org.telegram.abilitybots.api.bot;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.telegram.abilitybots.api.db.DBContext;
import org.telegram.telegrambots.meta.api.objects.User;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultAbilities_getUser_38c5370392_Test {

    @Mock
    private DBContext bot;

    @Mock
    private User user;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetUserSuccess() {
        long id = 123L;
        when(bot.users().get(id)).thenReturn(user);

        User result = getUser(id);

        assertEquals(user, result, "Expected and actual users should match");
    }

    @Test
    public void testGetUserFailure() {
        long id = 123L;
        when(bot.users().get(id)).thenReturn(null);

        assertThrows(IllegalStateException.class, () -> getUser(id), "Exception should be thrown when user is not found");
    }

    private User getUser(long id) {
        User user = bot.users().get(id);
        if (user == null) {
            throw new IllegalStateException(String.format("Could not find user corresponding to id [%d]", id));
        }

        return user;
    }
}
